---
- name: install update
  hosts: wsapp 
  #hosts: "{{ myhosts }}"
#  remote_user: ec2-user
  become: yes


  vars_files:
   - mariadb_vars.yaml

  tasks: 
  - name: Install Apache2
    apt: name=apache2 state=latest
  
  - name: Configure Website
    copy:
      src: "udacity-starter-website/"
      dest: "/var/www/html/"
    notify:
        - restart apache2
 

  - name: enabled mod_rewrite
    apache2_module: name=rewrite state=present
    notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
